### ISSUE TITLE
Maak het logo klikbaar

### ISSUE THREAD

**Issue by joostf** [Haroub-S/the-client-website#12]
https://github.com/Haroub-S/the-client-website/blob/47154e9549d3674c6af9fedf02b4c5b1db2ed3b9/index.html#L14-L16

Ipv een nietszeggend `div` element kan je hier een `a` element gebruiken. Met als voordeel dat je de bezoeker de mogelijkheid geeft om op elke moment terug te gaan naar de voorpagina.

**Comment by Haroub-S** [comment]
completed
