### ISSUE TITLE
Gebruik een button voor het menu

### ISSUE THREAD

**Issue by joostf** [Haroub-S/the-client-website#13]
https://github.com/Haroub-S/the-client-website/blob/47154e9549d3674c6af9fedf02b4c5b1db2ed3b9/index.html#L19-L23

Ipv een nietszeggend `div` element kan je hier een `button` element gebruiken om de bezoeker te kunnen laten interacteren met het menu.

**Comment by Haroub-S** [comment]
completed

**Comment by joostf** [comment]
Waar kan ik het resultaat zien @Haroub-S ?
