### ISSUE TITLE
Minder gebruik maken van CSS

### ISSUE THREAD

**Issue by joostf** [Haroub-S/the-client-website#15]
Je maakt in je HTML veelvuldig gebruik van classes. Tijdens dit semester zou ik je adviseren om dat niet te doen. Door minder classes te gebruiken wordt je uitgedaagd om beter na te denken over de structuur van de content, door CSS selectors te gebruiken die de hiërarchie van de HTML weergeven. En je leert meer over de basis van CSS zelf.

**Comment by Haroub-S** [comment]
top, bedankt.
